# Generated by Django 5.0.7 on 2024-08-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabla1',
            name='descripcion',
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name='tabla1',
            name='titulo',
            field=models.CharField(default=True, max_length=20),
        ),
    ]
